### ISSUE TITLE
The tool may omit some segments when extracting from SDLxliff

### ISSUE THREAD

**Issue by nesingwary-safari** [SuperBill888/GetTUsInfoSDLXLIFF#31]
# bug

I found a bug while testing this tool: the program may omit some sentences when extracting sdlxliff. After analyzing it, I found the root cause.
In sdlxliff, a`<seg-source>`tag pair may enclose multiple `<mrk>` segments.
Though the regex `mrk4match.findall(source_seg)` can find all the`<mrk>`instances, but it will put all the <mrk> segments in a single list.
For example.
`<seg-source><mrk mtype="seg" mid="5">sentence001</mrk> <mrk mtype="seg" mid="6">sentence002</mrk> <mrk mtype="seg" mid="7">sentence003</mrk> <mrk mtype="seg" mid="8">sentence004</mrk></seg-source>`
The regex will return a list like this
`[('5', 'sentence001'), ('6', 'sentence002'), ('7', 'sentence003'), ('8', 'sentence004')]` 

Then the code `tuinfo.append(smrks[0][1])` will only append `['sentence001']` into the list but abandon the rest elements.

I've fixed this issue by adding a condition:

```python
for source_seg in source_segs:
            smrks = mrk4match.findall(source_seg)
            if len(smrks) > 0:
                for smrk in smrks:
                    if len(smrk) >= 1:
                        smrk_new = [smrk[0:]]
                        tuinfo = []
                        tuinfo.append(smrk_new[0][1])
```

**Comment by SuperBill888** [comment]
Thank a lot for debug the script.
In what situation, there could be multi mrks in seg-source? beyond my experience, it should be only one string mrk between one seg-source, as seg-source means one segment of source. I guess you may segment and create the sdlxliff with different segment rules.
